### ISSUE TITLE
A few thoughts...

### ISSUE THREAD

**Issue by Raistlfiren** [kristophjunge/docker-mediawiki#1]
Hey, thanks for posting this code on github! I am hoping to use it to update an older wiki that we use for a game. When I was going through your implementation, I came across a few things that I might recommend.
- Include in the README how to override the default docker-composer file by using `docker-compose.override.yml`
- Adding to the previous thought, add the ability to add or override the existing `Dockerfile`
- Add `${DB_HOST}` as an environment variable that can be changed easily
- Separate/Remove all variables that are in `LocalSettings.php` that are not relevant to the build and place in `ExtraLocalSettings.php`
  - For example, `$wgGroupPermissions['*']['createaccount'] = false;` and etc...

Thank you for your time,

Rev

**Comment by kristophjunge** [comment]
Hello Rev,

thanks for trying to use my code.

1) Please note that the `docker-compose.yml` file in the root directory is only intended for development purposes. The variables in that file are defined in a `.env` file in root directory that you can create by copying `.env.default`.

I added two new docker-compose example files that i recommend to use. However all these files should be treated as examples and rather be copied then overridden.

The preferred way to use this image is to pull its build from Docker Hub.

Command Line:

```
docker pull kristophjunge/mediawiki:latest
```

Docker Compose:

```
version: '2'
services:
  wiki:
    image: kristophjunge/mediawiki:latest
```

2) If you have to extend the image the proper way is to create a `Dockerfile` that extends the build on Docker Hub. 

Dockerfile:

```
FROM kristophjunge/mediawiki:latest
```

I added a section "Extending this image" to the readme file.

3) The only place where variables in the form of ${} occur is in the docker-compose.yml in root directories which is again not intended to be used except for development.

To specify the database host for production use please use the environment variable.

Command-Line:

```
-e MEDIAWIKI_DB_HOST=dbhost
```

Docker Compose:

```
environment:
  MEDIAWIKI_DB_HOST: dbhost
```

4) I agree and have moved all configuration values that don't have a fixed default for a technical reason and that are not configurable by a docker environment variable into the default `ExtraLocalSettings.php` file. The moved configuration variables are $wgEnotifUserTalk, $wgEnotifWatchlist, $wgEmailAuthentication, $wgUseInstantCommons, $wgAuthenticationTokenVersion, $wgGroupPermissions.

If you still want to use this image please note that there are new versions with major changes. Have a look at the changelog.

Thank you,

Kristoph
