### ISSUE TITLE
Port 80 or 8080?

### ISSUE THREAD

**Issue by alex-dixon** [kristophjunge/docker-mediawiki#11]
Hi. Just pointing out the readme says app should be availble on localhost8080 but was changed to port 80. https://github.com/kristophjunge/docker-mediawiki/commit/e424da2d64e57f64c7aeb8e8997e4f11715fe808#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR6

**Comment by kristophjunge** [comment]
Previously it was meant to be 80 inside the container and 8080 outside for the examples. You pointed out that example and documentation were not completely aligned. Thanks!

Please note that in the latest version of the container i now have changed the port inside the container to 8080 as well.
