### ISSUE TITLE
mime.types not included

### ISSUE THREAD

**Issue by rlpowell** [kristophjunge/docker-mediawiki#14]
```
$ grep -i mime ./config/nginx/nginx-http.conf ./config/nginx/nginx-details.conf ./config/nginx/nginx-https.conf
$
```

The nginx conf doesn't, as far as I can tell, load /etc/nginx/mime.types at all.  This leads to things like uploaded PDFs being returned as text/plain.

**Comment by rlpowell** [comment]
Have further confirmed this.  My Dockerfile now includes:

```
RUN sed -ri 's!^\s*http \{\s*$!http {\n    include       /etc/nginx/mime.types;!' /etc/nginx/nginx-http.conf
```

which makes me feel dirty.  :)

**Comment by ZZerker** [comment]
Yep, had the same problem. Im not deep enough into docker, to find a elegant solution to this.

**Comment by herrmanthegerman** [comment]
@rlpowell : what exactly did you change/configure to allow PDF uploads in the first place? I'm still struggling at this stage, see #18 Thanks.

**Comment by rlpowell** [comment]
The PDFs were all already in the database from a previous server setup, sorry.

**Comment by herrmanthegerman** [comment]
Fixed issue #18 - not I'm stuck with this problem, PDFs get served as text/plain.

**Comment by rlpowell** [comment]
My second comment shows how to fix this.

**Comment by kristophjunge** [comment]
The mime types are now correctly set in the nginx configuration.

**Comment by rlpowell** [comment]
Confirmed, thanks!
