### ISSUE TITLE
Install Problems: Cannot access the database

### ISSUE THREAD

**Issue by ghost** [kristophjunge/docker-mediawiki#15]
Hi,
when i follow your documentation on DockerHub, i get an issue when i run the install script.
I get the error: _"Cannot access the database: Access denied for user 'wikiuser'@'172.17.0.6' (using password: YES) (mysql-server). Check the host, username and password and try again."_

What can i do to solve the issue?

Many thanks for your answers

**Comment by ghost** [comment]
Clean out your '/srv/mediawiki/mysql' folder on your docker host. That helped me.

**Comment by kristophjunge** [comment]
Please execute the following 4 commands. That should give a working installation.

```
docker run --name=mediawiki_mysql \
-e MYSQL_DATABASE=wikidb \
-e MYSQL_USER=wikiuser \
-e MYSQL_PASSWORD=mysecret \
-e MYSQL_RANDOM_ROOT_PASSWORD=1 \
-v /var/mediawiki/mysql:/var/lib/mysql \
-d mysql:5.7

docker run --name mediawiki_wiki \
--link mediawiki_mysql:mediawiki_mysql \
-p 8080:8080 \
-e MEDIAWIKI_SERVER=http://localhost:8080 \
-e MEDIAWIKI_SITENAME=MyWiki \
-e MEDIAWIKI_LANGUAGE_CODE=en \
-e MEDIAWIKI_DB_TYPE=mysql \
-e MEDIAWIKI_DB_HOST=mediawiki_mysql \
-e MEDIAWIKI_DB_PORT=3306 \
-e MEDIAWIKI_DB_NAME=wikidb \
-e MEDIAWIKI_DB_USER=wikiuser \
-e MEDIAWIKI_DB_PASSWORD=mysecret \
-e MEDIAWIKI_ENABLE_UPLOADS=1 \
-v /var/mediawiki/images:/images \
-d kristophjunge/mediawiki

docker exec -it mediawiki_wiki /script/install.sh admin admin123_
```

Login under http://localhost:8080 with username `admin` and password `admin123_`.
