### ISSUE TITLE
/images not writable for webserver process

### ISSUE THREAD

**Issue by herrmanthegerman** [kristophjunge/docker-mediawiki#17]
Hi there,
I'm new to Docker. Additionally, I'm running Docker on a Synology NAS. This might be a different flavour as on regular Linux systems. So please beware.

After following the [instructions](https://github.com/kristophjunge/docker-mediawiki), I got the container up and running. The visual editor works like a charm. Awesome! 

However, when I tried to upload an image, I got a strange error message: "Could not store upload in the stash (UploadStashFileException): "Error storing file in '/tmp/phpxQt4k1': Could not create directory"

I opened a shell on the running container and indeed, `/images` was not accessible for user` www-data`:
`drwxr-xr-x   1     1024 users       0 Jan 18 12:07 images`

According to `/etc/passwd`, there's no user with id 1024 (`www-data` is 999).

To resolve this issue in a quick&dirty manner, I set the permission of the folder to 777:
`chmod 777 /images`

Now uploading images works.

Any idea why the permissions might be wrong in my container?

**Comment by kristophjunge** [comment]
I fixed the problem in the scope of issue #10. Thanks for reporting!
