### ISSUE TITLE
MEDIAWIKI_FILE_EXTENSIONS issue: Cannot upload PDF file

### ISSUE THREAD

**Issue by herrmanthegerman** [kristophjunge/docker-mediawiki#18]
I installed this image/docker on my Synology NAS. It's working and I even managed to upload an image to a wiki page using drag & drop. 

Then I tried to upload PDF files, too, and failed.

According to [MediaWiki manual](https://www.mediawiki.org/wiki/Manual:$wgFileExtensions), the default list of allowed extensions is 'png', 'gif', 'jpg', 'jpeg', 'webp' and all others are blocked. To add more extensions, this container provides the environment variable [MEDIAWIKI_FILE_EXTENSIONS](https://github.com/kristophjunge/docker-mediawiki). 

Although I set the environment variable
`MEDIAWIKI_FILE_EXTENSIONS=png,gif,jpg,jpeg,doc,xls,mpp,pdf,ppt,tiff,bmp,docx,xlsx,pptx,ps,odt,ods,odp,odg`
I get an error when uploading a PDF file (see screenshot). Why is this and is this a image/container issue or rather a MediaWiki issue?

![image](https://user-images.githubusercontent.com/26109745/35105760-c12da686-fc6c-11e7-8a87-b0dbf7d6a6c9.png)

**Comment by hexmode** [comment]
replied on your mw support ticket.  From what you posted there, it looks like you need a space after the commas in your extension list. https://www.mediawiki.org/w/index.php?title=Topic:U6dip8vqkfy90baf&topic_showPostId=u6pku5avs8yvc33j#flow-post-u6pku5avs8yvc33j

**Comment by herrmanthegerman** [comment]
Thanks @hexmode , that did the trick. 

This should be mentioned in the documentation OR in LocalSettings.php the explode() part could be relaxed to use a comma without space as separator (as the following trim() removes whitespace from both "sides" of a string).

**Comment by kristophjunge** [comment]
Indeed the implementation required spaces. Now both is supported, spaces or an without spaces. Apart from that i added a little more documentation regarding uploads.
