### ISSUE TITLE
Specifying ExtraLocalSettings.php results in displaying contents of extralocalsettings.php

### ISSUE THREAD

**Issue by nmartin84** [kristophjunge/docker-mediawiki#26]
Hi,

First off great image, and thanks for making this available for all of us. I did run into an issue when I tried defining some custom settings in my `ExtraLocalSettings.php`. I'm loading a custom skin "Timeless" by following your directions and mounting the following 2:
`-v /var/mediawiki/skins/Timeless:/var/www/mediawiki/skins/Timeless:ro` 
`-v /var/mediawiki/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro `

My ExtraLocalSettings.php is very simple and looks like this (I also tried copying the ExtraLocalSettings.php form inside the container).

`wfLoadSkin( 'Timeless' );`

But when I launch the container and browse to the site, I get a blank page that displays the contents of ExtraLocalSettings.php. Any ideas?

**Comment by JeanPatrickVrel** [comment]
Hello there,
Just had a similar problem (wanted to use timeless skin), and managed to make it work. It is not a solution for the ExtrLocalSettings though, but I think it might interest you. First make sure that you have the correct version of TimeLess. The last ones require a version of MediaWiki that is 3.14 I think (I did not double-check) which is higher than the one used in this docker. So make sure you downloaded the correct one. This one should work :
https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/skins/Timeless/+/REL1_30
Second, you have to be sure rstudio-server has the correct rights on the /var/mediawiki/skins/Timeless folder. A bit of sudo chown -R rstudio-server /var/mediawiki/skins/Timeless should do the work. You do not need to use the -v /var/mediawiki/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro command.
Cheers,
JP

**Comment by nmartin84** [comment]
> Hello there,
> Just had a similar problem (wanted to use timeless skin), and managed to make it work. It is not a solution for the ExtrLocalSettings though, but I think it might interest you. First make sure that you have the correct version of TimeLess. The last ones require a version of MediaWiki that is 3.14 I think (I did not double-check) which is higher than the one used in this docker. So make sure you downloaded the correct one. This one should work :
> https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/skins/Timeless/+/REL1_30
> Second, you have to be sure rstudio-server has the correct rights on the /var/mediawiki/skins/Timeless folder. A bit of sudo chown -R rstudio-server /var/mediawiki/skins/Timeless should do the work. You do not need to use the -v /var/mediawiki/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro command.
> Cheers,
> JP

Appreciate the response. I was suspecting it was a permission issue caused by windows and I think you helped confirm that. I've moved onto creating my own docker containers and ill probably come around to building an image for mediawiki here soon.
