### ISSUE TITLE
Failed to start Container

### ISSUE THREAD

**Issue by virtualweb-at** [kristophjunge/docker-mediawiki#6]
Hi,

it is not possible to start this Container, the Message gives:
```
Error response from daemon: containerd: container not started
Error: failed to start containers: mediawiki
```
**journalctl -f -u docker.service** gives:
```
May 11 18:01:11 xxxxx.com dockerd[1422]: time="2017-05-11T18:01:11.130133084+02:00" level=error msg="Handler for POST /v1.24/containers/mediawiki/start returned error: containerd: container not started"
```

According to another Thread (https://github.com/moby/moby/issues/31437) the reason could be the Fact, that the Entrypoint Script has no Executable Bit set?

**Comment by kristophjunge** [comment]
I could not confirm that the entrypoint doesent have the executable bit. The entrypoint is executable in the sources and in the resulting container as well.

Test in sources:

```
git clone https://github.com/kristophjunge/docker-mediawiki.git
cd docker-mediawiki
ls -al script/
drwxrwxr-x 2 username username 4096 Jun 16 07:47 .
drwxrwxr-x 8 username username 4096 Jun 16 08:07 ..
-rwxrwxr-x 1 username username 1148 Jun 16 07:47 docker-entry.sh
-rwxrwxr-x 1 username username  924 Jun 16 07:47 install.sh
-rwxrwxr-x 1 username username  156 Jun 16 07:47 update.sh
```

Test in running container (Assumed that your MediaWiki container is namend "mediawiki"):

```
docker exec -it mediawiki bash
ls -al /script/
drwxr-xr-x   2 root root 4096 Dec 17 21:37 .
drwxr-xr-x 109 root root 4096 Jun 15 22:00 ..
-rwxr-xr-x   1 root root 1148 Dec 17 21:27 docker-entry.sh
-rwxr-xr-x   1 root root  924 Dec 17 21:27 install.sh
-rwxr-xr-x   1 root root  156 Dec 17 21:27 update.sh
```

Could you please provide your configuration and the logs of your MediaWiki container? I will look into your issue.

```
docker inspect mediawiki
docker logs mediawiki
```

Dont forget to trim out any sensitive data.
