### ISSUE TITLE
Documentation incomplete for -e variables

### ISSUE THREAD

**Issue by SoftNotWork** [kristophjunge/docker-mediawiki#7]
The documentation is incomplete and does not finish with a working Docker based MediaWiki install.

The trouble starts with the way the environment variables are presented. It is step by step with editable commands then ends into -e for this and -e for that with no presentation on how to use these. This should be corrected to show methods on how to incorporate the various additional -e variables. This should be made plain for newer Docker users who are not veterans of the system. 

The strategy appears to be to take multiple attempts at docker -run, delete if you get it wrong, and there is no way to edit the -e after the first docker -run.

**Comment by herrmanthegerman** [comment]
I'm new to docker so please beware.

I do not understand why you write "there is no way to edit the -e after the first docker run".

It is my understanding that the concept of setting environment variables (-e does this) is to provide a configuration that IS changeable from docker run to docker run. Just run the container with a different environment. For example in this image/container, mediawiki's configuration file "LocalSettings.php" has been adapted to read the environment variables (as listed [here](https://hub.docker.com/r/kristophjunge/mediawiki/)) and applies them to the respective MediaWiki configuration settings.

**Comment by kristophjunge** [comment]
The most convenient approach to bring configuration into docker containers is probably using environment variables. Depending on you platform (plain docker, docker-compose, kubernetes, ...) there are different ways to setup environment variables. In the documentation iam using environemnt variables that are passed on command line to the plain docker command. However if you are using docker-compose there is an example [configuration](https://github.com/kristophjunge/docker-mediawiki/blob/master/example/docker-compose/mysql/docker-compose.yml).

I understand that people without much docker experience simply want to use MediaWiki but that is basic docker knowledge which i cannot provide. Ive added a link to the the official docker [documentation](https://docs.docker.com/) to give at least a hint. 

The container is using environment variables as the main approach but as described [here](https://github.com/kristophjunge/docker-mediawiki#configuration-file) you can also use a standard MediaWiki configuration file. Additionally to the configuration sections in the documentation "General", "HTTPS", "Uploads", "E-Mail", "Logo", "Skins", "Extensions" there is a list of all supported environment variables [here](https://github.com/kristophjunge/docker-mediawiki#configuration-reference).

For more details of the options or when using a MediaWiki configuration file please refer to the MediaWiki [documentation](https://www.mediawiki.org/wiki/Manual:Configuration_settings).

Also have a look [here](https://github.com/kristophjunge/docker-mediawiki#additional-configuration) if you want to use configuration options that are not supported by the containers environment variables.

It should be possible to get a running MediaWiki just by executing the commands from the usage sections. If you look at the environment variables in these commands you should be able to modify them and incooperate others.

Let me know if its still not working for you.
